let array = [

    {firstName : "Romil",
    lastName:"Ghadge",
    address:"Lalbaug",
    city:"Mumbai",
    state:"Maharashtra",
    zipcode:"400012",
    phoneNumber:"9594787715",
    email:"romilfgh11@gmail.com"},
    {firstName:"Ayush",
    lastName:"Treimb",
    address:"Ramdoot",
    city:"Chennai",
    state:"Maharshtra",
    zipcode:"400012",
    phoneNumber:"9876678945",
    email:"ayush11@gmail.com"},
    {firstName:"Aniket",
    lastName:"Jadhav",
    address:"Ramdoot",
    city:"Mumbai",
    state:"Maharshtra",
    zipcode:"400012",
    phoneNumber:"9876678945",
    email:"anijas11@gmail.com"},
    {firstName:"Akshay",
    lastName:"Tawde",
    address:"Borivali",
    city:"Chennai",
    state:"Maharshtra",
    zipcode:"400012",
    phoneNumber:"9876678945",
    email:"ayush11@gmail.com"},
    {firstName:"Sai",
    lastName:"Palekar",
    address:"Neral",
    city:"Nashik",
    state:"Maharshtra",
    zipcode:"400012",
    phoneNumber:"9876678945",
    email:"ayush11@gmail.com"},

]

let newArray = array.filter(person => person.city == "Mumbai").forEach(person => {console.log(person)});